### ISSUE TITLE
Eight tests that pass on Ubuntu 23.04 fail on Debian 11.6

### ISSUE THREAD

**Issue by jdykstra** [jdykstra/ucsd-psystem-fs#2]
At 0486686 (meson build mods), these tests fail on Debian 11.6:

 3/26 t0003a FAIL           0.14s (exit status 1)
 3/26 t0003a FAIL           0.14s (exit status 1)
 4/26 t0005a FAIL           0.17s (exit status 1)
 4/26 t0005a FAIL           0.17s (exit status 1)
 8/26 t0009a FAIL           0.11s (exit status 1)
 8/26 t0009a FAIL           0.11s (exit status 1)
 9/26 t0010a FAIL           0.13s (exit status 1)
 9/26 t0010a FAIL           0.13s (exit status 1)

From a quick look, it appears that the tests can't find their helper programs (test_statfs and test_rdwr).  On Debian, the PATH used to execute the test is:

23:01:58 PATH='/home/jwd/working/fs-workspace/ucsd-psystem-fs/script:/home/jwd/ucsd_tools/installed/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games' /usr/bin/sh /home/jwd/working/fs-workspace/ucsd-psystem-fs/build/../test/00/t0005a.sh

On Ubuntu 23.04, the PATH used to execute the test is:

PATH=/home/jwd/working/fs-workspace/ucsd-psystem-fs/script:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_umount:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_text:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/test_statfs:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/test_rdwr:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_rt11:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_mount:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_mkfs:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_logo:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_interleave:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_fsck:/home/jwd/working/fs-workspace/ucsd-psystem-fs/build/ucsdpsys_disk:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/jwd/usr/bin:/home/jwd/usr/local/bin:/home/jwd/usr/bin:/home/jwd/usr/local/bin MALLOC_PERTURB_=204 /usr/bin/sh /home/jwd/working/fs-workspace/ucsd-psystem-fs/build/../test/00/t0005a.sh

The meson version on Debian is 0.56.2.  The meson version on Ubuntu is 1.0.1.

**Comment by eli-schwartz** [comment]
#3 adds a minimum version newer than 0.56.2 but older than 1.0.1 based on meson's own warnings for feature availability.

> uses feature introduced in '0.58.0': Overriding previous value of environment variable 'PATH' with a new one.

That should be sufficient, I think.
